version: "3.8"

services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    ports:
      - "3306:3306"
    networks:
      - almacen-network
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost --silent"]
      interval: 10s
      retries: 5

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile.eureka-server
    ports:
      - "8761:8761"
    networks:
      - almacen-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 20s
      timeout: 10s
      retries: 15

  productos:
    build:
      context: ./productos
      dockerfile: Dockerfile.productos
